name: Build UEFI Greeter

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build inside official Rust container
      run: |
        docker run --rm -v ${{ github.workspace }}:/volume -w /volume rust:1.65.0-slim-bullseye sh -c "
          rustup target add x86_64-unknown-uefi &&
          cargo build --release --target x86_64-unknown-uefi
        "

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: opal-uefi-greeter-bin
        path: target/x86_64-unknown-uefi/release/opal_uefi_greeter.efi
